==== Plugin Konfiguration

Es gibt keine Konfiguration des Plugins

==== Konfiguration von Geräten

Es ist notwendig, Zugangsinformationen für die Mail-Box zur Verfügung zu stellen :

  Konto : Benutzer-Konto (je nach Box, kann es zum Beispiel der Name vor dem @ sein oder die ganze Adresse)

  Passwort: das Passwort

  Server : die Adresse des Mail-Servers

  Port : der Port des Imap-Servers

  Anhänge : giebt an, wie Anlagen behandelt werden sollen

La sauvegarde de l'équipement va automatiquement faire démarrer l'écoute de la boite mail


==== Geräte Informationen

Folgende Informationen sind verfügbar :

  Absender: Absender der Mail

  Thema: Thema

  Hauptteil : der Hauptteil der e-Mail, im Textarea Format 

  HTML : das Äquivalent in HTML

  Anhang : Wenn die Anlagen verarbeitet wird, den Backup-Pfad der Anlage angeben (für eine Verarbeitung mit Datatransfert zum Beispiel)  

Les différentes informations sont de type évènementiel dès qu'un mail est recu l'information est enregistrée. On peut donc utiliser les différentes infos en déclencheur de scénario et en testant leur valeur.