==== Configuration du plugin

Il n'y a pas de configuration du plugin

==== Configuration d'un équipement

Il est nécessaire de fournir les informations d'accès à la boite mail :

  Compte : le compte à utiliser (suivant la boite, ca peut être par exemple le nom devant @ ou bien toute l'adresse)

  Mot de passe : le mot de passe quoi

  Serveur : l'adresse du serveur mail

  Port : le port du serveur imap

  Pièces jointes : indique si les pièces jointes doivent être traitées

La sauvegarde de l'équipement va automatiquement faire démarrer l'écoute de la boite mail


==== Informations d'un équipement

Les informations suivantes sont disponibles :

  Expéditeur : l'expéditeur du mail

  Sujet : le Sujet

  Corps : le corps du mail en format textarea

  HTML : l'équivalent en HTML

  Pièce jointe : quand les pièces jointes sont traitées, donnent le chemin de sauvegarde de la pièce jointe (pour un traitement par datatransfert par exemple)

Les différentes informations sont de type évènementiel : dès qu'un mail est reçu, l'information est enregistrée. On peut donc utiliser les différentes infos en déclencheur de scénario et en testant leur valeur.
